# Generated by Django 3.1.1 on 2020-09-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_personfiles_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='freq',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='person',
            name='min_stars',
            field=models.IntegerField(default=2),
        ),
    ]
