# Generated by Django 3.1.1 on 2020-10-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20200930_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prices',
            field=models.CharField(default='Full', max_length=20),
        ),
        migrations.CreateModel(
            name='PersonFilesAlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership', models.CharField(max_length=100)),
                ('model', models.TextField()),
                ('price_msrp', models.IntegerField()),
                ('url', models.URLField()),
                ('email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interface.person')),
            ],
        ),
    ]
